name: build
on:
    push:
        paths:
            - 'build/**'
            - '.github/workflows/**'

jobs:
    build_ios:
        runs-on: macos-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2
              
            - name: run build command
              run: |   
                  cd build
                  ./make_ios.sh
                  git pull
               
            - name: post build
              if: ${{ success() }}
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                 commit_message: "[Auto build]ios library"
                 file_pattern: Assets/Plugins/iOS/*.a
