name: build
on:
    push:
        paths:
            - 'build/**'
            - '.github/workflows/**'
          
jobs:
    build_win:
        runs-on: windows-2016

        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: run build command
              run: |   
                  cd build
                  .\make_win.bat
