name: build
on:
    push:
        paths:
            - 'build/**'
            - '.github/workflows/**'
          
jobs:
    build_win:
        runs-on: windows-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.1
              with:
                  vs-version: '15'
            - name: run build command
              run: |   
                  cd build
                  .\make_win.bat
