name: build
on:
    push:
        paths:
            - 'build/**'
            - '.github/workflows/**'
          
jobs:
    build_android:
        runs-on: ubuntu-18.04
        
        steps:
            - name: checkout
              uses: actions/checkout@v2
              
            - name: Prepare NDK dir for caching
              run: |
                sudo mkdir -p /usr/local/lib/android/sdk/ndk
                sudo chmod -R 777 /usr/local/lib/android/sdk/ndk
                sudo chown -R $USER:$USER /usr/local/lib/android/sdk/ndk
                  
            - name: NDK Cache
              id: ndk-cache
              uses: actions/cache@v2
              with:
                  path: /usr/local/lib/android/sdk/ndk
                  key: ndk-cache-r15c-linux

            - name: Install NDK
              if: steps.ndk-cache.outputs.cache-hit != 'true'
              run: |
                  cd /usr/local/lib/android/sdk/ndk
                  curl -O https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
                  unzip android-ndk-r15c-linux-x86_64.zip
              
            - name: run build command
              env:
                  NDKPATH: /usr/local/lib/android/sdk/ndk/android-ndk-r15c
                  ANDROID_NDK: /usr/local/lib/android/sdk/android-ndk-r15c
              run: |
                  cd build
                  ./make_android.sh
                  
            - name: commit build
              if: ${{ success() }}
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git commit Assets/Plugins/Android/libs/armeabi-v7a/libslua.so Assets/Plugins/Android/libs/armeabi-arm64/libslua.so Assets/Plugins/Android/libs/x86/libslua.so -m "[Auto build]android so"
                
            - name: push build
              if: ${{ success() }}
              uses: ad-m/github-push-action@master
              with:
                 github_token: ${{ secrets.GITHUB_TOKEN }} 
