name: build
on:
    push:
        paths:
            - 'build/**'
            - '.github/workflows/**'
          
jobs:
    build_win:
        runs-on: windows-2016

        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: run build command
              run: |   
                  cd build
                  .\make_win.bat
            - name: commit build
              if: ${{ success() }}
              run: |
                git commit Assets/Plugins/x64/slua.dll Assets/Plugins/x86/slua.dll -m "[Auto build]windows dll"
            - name: push build
              if: ${{ success() }}
              uses: ad-m/github-push-action@master
              with:
                 github_token: ${{ secrets.GITHUB_TOKEN }}
